################################### builder ####################################
FROM node:10.16-alpine

RUN mkdir /app
WORKDIR /app

COPY ./client/package.json .
COPY ./client/yarn.lock .

RUN yarn install

COPY ./client/* .

RUN yarn run build

#################################### runner ####################################
FROM nginx

COPY ./app/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./app/nginx/default.conf /etc/nginx/conf.d/default.conf

COPY ./app/build /usr/share/nginx/html
COPY ./app/build /usr/share/nginx/html/app/