version: 3
services:
  client:
    container_name: app-react-client
    build: ./client
    ports:
      - 3000:80
    links:
      - server
    stdin_open: true

  server:
    container_name: app-node-express
    build: ./server
    ports: 
      - 1337:1337
    links:
      - mongo
      
  mongo:
    hostname: mongo
    image: mongo
    ports:
      - 27017:27017
    